# Generated by Django 5.2.4 on 2025-07-28 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g.\xa0+989336628244 or 09336628244).', regex='^(?:\\+?\\d{1,3})?[0]?\\d{9,14}$')]),
        ),
    ]
