# Generated by Django 5.2.5 on 2025-08-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_user_sms', models.BooleanField(default=True)),
                ('enable_manager_sms', models.BooleanField(default=True)),
                ('manager_phones', models.JSONField(blank=True, default=list, help_text='List of manager phone numbers')),
                ('user_sms_template', models.TextField(default='سلام {{ user.first_name }}؛ اشتراک شما برای پلن {{ plan.name }} در تاریخ {{ end_jalali }} تمام شد.')),
                ('manager_sms_template', models.TextField(default='اشتراک {{ user.get_full_name }} ({{ user.username }}) در {{ end_jalali }} منقضی شد.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Notifications',
                'verbose_name_plural': 'Subscription Notifications',
            },
        ),
    ]
