# Generated by Django 5.2.5 on 2025-08-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriptionnotificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionnotificationconfig',
            name='manager_phones',
            field=models.JSONField(blank=True, default=list, help_text='List of manager phone numbers (e.g., 09xxxxxxxxx).'),
        ),
        migrations.AlterField(
            model_name='subscriptionnotificationconfig',
            name='manager_sms_template',
            field=models.TextField(default='اشتراک کاربر {{ user.get_full_name }} (تا {{ end_jalali }}) منقضی شد.'),
        ),
        migrations.AlterField(
            model_name='subscriptionnotificationconfig',
            name='user_sms_template',
            field=models.TextField(default='اشتراک شما تا {{ end_jalali }} بوده و اکنون منقضی شده است. برای تمدید اقدام کنید.'),
        ),
    ]
