# Generated by Django 5.2.5 on 2025-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscriptionnotificationconfig_manager_phones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionnotificationconfig',
            name='enable_manager_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionnotificationconfig',
            name='manager_email_subject',
            field=models.CharField(default='اشتراک منقضی شد', max_length=200),
        ),
        migrations.AddField(
            model_name='subscriptionnotificationconfig',
            name='manager_email_template',
            field=models.TextField(default='اشتراک کاربر {{ user.get_full_name }} (تا {{ end_jalali }}) منقضی شد.'),
        ),
        migrations.AddField(
            model_name='subscriptionnotificationconfig',
            name='manager_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of manager email addresses.'),
        ),
    ]
