# Generated by Django 5.2.5 on 2025-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscriptionnotificationconfig_enable_manager_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_code_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
