# Generated by Django 5.2.5 on 2025-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_otp_code_customuser_otp_code_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
