# Generated by Django 5.2.1 on 2025-06-14 19:48

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('sopfile', models.FileField(blank=True, null=True, upload_to=pages.models.directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='SOP file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datetime_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
