# Generated by Django 5.2.5 on 2025-12-05 16:39

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sopfile',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx']), django.core.validators.MinValueValidator(1)], verbose_name='SOP file'),
        ),
    ]
