# Generated by Django 5.2.1 on 2025-06-16 18:22

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sopfile',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])], verbose_name='SOP file'),
        ),
    ]
