# Generated by Django 5.2.4 on 2025-08-04 17:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorgroupsessionparticipant',
            old_name='present',
            new_name='learner_present',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='urls',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='url',
            field=models.URLField(default=1, help_text='The address of the post.', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorgroupsessionoccurrence',
            name='reason_for_change',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='platform',
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stepextension',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepprogresssession',
            name='recorded_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskevaluation',
            name='score_numeric',
            field=models.PositiveSmallIntegerField(help_text='Select from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='courses.socialmedia'),
            preserve_default=False,
        ),
    ]
