# Generated by Django 5.2.4 on 2025-07-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnersubscribeplan',
            name='duration_in_days',
        ),
        migrations.AlterField(
            model_name='sessiontemplate',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to='courses.learningpath'),
        ),
        migrations.AlterField(
            model_name='sessiontemplate',
            name='mentor_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to='courses.mentorassignment'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='skipped',
            field=models.BooleanField(default=False, help_text='If you make skip to True then the initial_promise_days MUST be 0!'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_in_days',
            field=models.PositiveSmallIntegerField(choices=[(30, '30\xa0days'), (90, '90\xa0days'), (120, '120\xa0days'), (270, '120\xa0days'), (360, '120\xa0days')]),
        ),
    ]
