# Generated by Django 5.2.4 on 2025-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorgroupsessionocuurence',
            options={'ordering': ('-occurence_datetime',)},
        ),
        migrations.RemoveField(
            model_name='mentorgroupsessionocuurence',
            name='google_meet_record',
        ),
        migrations.AddField(
            model_name='mentorgroupsessionocuurence',
            name='session_video_record',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mentorgroupsessionocuurence',
            index=models.Index(fields=['mentor_group_session', 'occurence_datetime'], name='courses_men_mentor__0420c5_idx'),
        ),
    ]
