# Generated by Django 5.2.4 on 2025-08-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_present_mentorgroupsessionparticipant_learner_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorgroupsessionparticipant',
            old_name='learner_present',
            new_name='was_learner_present',
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='url',
            field=models.URLField(blank=True, help_text='The address of the post.', max_length=500, null=True),
        ),
    ]
