# Generated by Django 5.2.4 on 2025-07-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_learnersubscribeplan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
