# Generated by Django 5.2.5 on 2025-08-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_learnerenrolment_learner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallearnersubscribeplan',
            old_name='learner_enrolment',
            new_name='learner_enrollment',
        ),
        migrations.RenameField(
            model_name='historicalsubscriptiontransaction',
            old_name='learner_enrolment',
            new_name='learner_enrollment',
        ),
        migrations.RenameField(
            model_name='learnersubscribeplan',
            old_name='learner_enrolment',
            new_name='learner_enrollment',
        ),
        migrations.RenameField(
            model_name='mentorassignment',
            old_name='enrolment',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='subscriptiontransaction',
            old_name='learner_enrolment',
            new_name='learner_enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('enrollment', 'mentor', 'start_date')},
        ),
    ]
