# Generated by Django 5.2.4 on 2025-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_mentorgroupsessionocuurence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorgroupsessionocuurence',
            name='session_video_record',
            field=models.URLField(blank=True, help_text='The link for downloading the record of the session.', null=True),
        ),
    ]
