# Generated by Django 5.2.5 on 2025-08-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_learner_enrolment_historicallearnersubscribeplan_learner_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnerEnrolment',
            new_name='LearnerEnrollment',
        ),
        migrations.RenameIndex(
            model_name='learnerenrollment',
            new_name='courses_lea_learnin_b66550_idx',
            old_name='courses_lea_learnin_03aaf9_idx',
        ),
    ]
