# Generated by Django 5.2.4 on 2025-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_learner_present_mentorgroupsessionparticipant_was_learner_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorgroupsessionparticipant',
            name='was_learner_present',
        ),
        migrations.AddField(
            model_name='mentorgroupsessionparticipant',
            name='learner_was_present',
            field=models.BooleanField(default=True, help_text='off -> absent, on -> present.'),
        ),
    ]
