# Generated by Django 5.2.4 on 2025-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_dob_learner_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='specialties',
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='courses.specialty'),
        ),
    ]
