# Generated by Django 5.2.5 on 2025-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_learnerenrolment_learnerenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='courses.feature'),
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
