# Generated by Django 5.2.4 on 2025-08-04 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_mentorgroupsessionparticipant_was_learner_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevaluation',
            name='score_numeric',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1, help_text='Select from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
