# Generated by Django 5.2.5 on 2025-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subscriptionplan_features_delete_planfeature'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['subscription', 'paid_at', 'id'], name='courses_sub_subscri_c5cfb4_idx'),
        ),
    ]
