# Generated by Django 5.2.4 on 2025-08-04 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_taskevaluation_score_numeric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskevaluation',
            old_name='feedback_text',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='taskevaluation',
            name='score_numeric',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1, help_text='\n        <b>⚖️Stars will increase if:</b>\n        <br>\n        1- Completed the task.\n        <br>\n        2- Task has doc/readme file and is published on the github.\n        <br>\n        3- Deadline was honored.\n        <br>\n        4- Learner inform the mentro before he deadline.\n        <br>\n        5- There is creativity and perfection.\n        ', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
