# Generated by Django 5.2.4 on 2025-08-04 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_feedback_text_taskevaluation_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='hire_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
