# Generated by Django 5.2.5 on 2025-11-13 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subscriptiontransaction_courses_sub_subscri_c5cfb4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
