# Generated by Django 5.2.4 on 2025-08-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_mentor_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskevaluation',
            old_name='score_numeric',
            new_name='score',
        ),
    ]
