# Generated by Django 5.2.5 on 2025-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_tasksubmission_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorassignment',
            name='code_review_pro_session_datetime',
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='The link for joining the meeting session.'),
        ),
    ]
