# Generated by Django 5.2.4 on 2025-08-04 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_score_numeric_taskevaluation_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskevaluation',
            name='valid_score_range',
        ),
        migrations.AlterField(
            model_name='stepextension',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='taskevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='valid_score_range'),
        ),
    ]
