# Generated by Django 5.2.5 on 2025-12-05 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_internal', models.BooleanField(default=False)),
                ('event', models.CharField(choices=[('other', 'Other'), ('new_evaluation', 'New mentor evaluation added'), ('new_submission', 'Task submission created'), ('deadline_approaching', 'Deadline approaching'), ('extension_requested', 'Extension requested'), ('group_session_rescheduled', 'Group session rescheduled'), ('marked_absent', 'Learner marked absent'), ('mentor_assigned', 'Mentor assigned to a learner'), ('subscription_purchased', 'Subscription purchased'), ('subscription_expiring', 'Subscription near expiry'), ('subscription_expired', 'Subscription expired'), ('subscription_frozen', 'Subscription frozen')], default='other', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
            },
        ),
    ]
